version: "3"
services:
  api:
    image: monemmono/flutter_workshop_2122:1
    environment:
      - NODE_ENV=production
    ports:
      - "9090:9090"
    networks:
      - flutter_workshop_2122
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - database:/data/db
    networks:
      - flutter_workshop_2122
volumes:
  database:
networks:
  flutter_workshop_2122: